DROP DATABASE IF EXISTS taskwiz;
CREATE DATABASE taskwiz;

USE taskwiz;

CREATE TABLE User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);